# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Build
      run: go build -o k8x .
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        path: ./k8x
    - name: Create tag
      id: create_tag
      run: |
        tag_name="v0.1.${{ github.run_number }}-alpha"
        git tag $tag_name
        git push origin $tag_name
    - name: Create github release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v0.1.${{ github.run_number }}-alpha"
        files: k8x
